USE vitrine_virtual_todo5;

CREATE TABLE IF NOT EXISTS tbProdutos
(ID_PRODUTO INT NOT NULL AUTO_INCREMENT,
NOME VARCHAR(100),
DESCRICAO VARCHAR(150),
ID_FORNECEDOR INT,
CATEGORIA VARCHAR(50),
TAMANHO VARCHAR(10),
PRECO FLOAT,
SUSTENTAVEL BIT,
QTD_ESTOQUE SMALLINT,
PRIMARY KEY (ID_PRODUTO)
);